### ISSUE TITLE
Hope to support vue3

### ISSUE THREAD

**Issue by yswf** [Sarmerer/vue-gantt-chart#1]
I tried to introduce this component in vue3, but when I drag and add Task, it cannot be displayed completely.

**Comment by Sarmerer** [comment]
When I were writing this component, I tried  to split the logic and renderer as much as possible, to allow easier porting to other frameworks and libraries. So, it should relatively easy to rewrite current [renderer](https://github.com/Sarmerer/vue-gantt-chart/blob/fa80bf3d546ad28d53df4dc738c1dbcf1887d277/src/components/GanttChart/index.vue)  to Vue 3 syntax

**Comment by yswf** [comment]
> When I were writing this component, I tried to split the logic and renderer as much as possible, to allow easier porting to other frameworks and libraries. So, it should relatively easy to rewrite current [renderer](https://github.com/Sarmerer/vue-gantt-chart/blob/fa80bf3d546ad28d53df4dc738c1dbcf1887d277/src/components/GanttChart/index.vue) to Vue 3 syntax

##### I am very much in favor of deconstructing and separating the code. For your core logic code, it is not related to any framework. But in your vue2 demo (vu3 version also has this problem): Due to the vue responsive principle, there is a problem of repeated nesting of Task objects, which greatly reduces program performance,It is easy to overflow memory。

###### You can console.log the task object under line 320 of index.vue and you will find the problem

```javascript
  this.taskSpawnData.task = task;
      console.log(task);
      task.resizeStart(SIDES.right, event, {
        resizeEndCallback: this.spawnTaskModalShow,
      });
```
###### get the task as
```javascript
{
        id: "ead5b6dd-d0d8-4408-ac07-083d67116e2b",
        name: "New task",
        start: 1642000380,
        end: 1642000440,
        resource: "resource-4f34bd31-4ede-4fc0-a44f-8c04e41c6301",
        chart: {
          tasks: [
            {
              id: "6b85183b-fe28-4e83-9f04-6834036cf446",
              name: "Task 1",
              start: 1641945600,
              end: 1642125600,
              resource: "resource-82219cbb-62f1-4533-8846-4181299fbf3d",
              chart: {
                tasks: [
                  {
                    id: "6b85183b-fe28-4e83-9f04-6834036cf446",
                    name: "Task 1",
                    start: 1641945600,
                    end: 1642125600,
                    resource: "resource-82219cbb-62f1-4533-8846-4181299fbf3d",
                    chart: {
                      tasks: [
                        {
                          id: "6b85183b-fe28-4e83-9f04-6834036cf446",
                          name: "Task 1",
                          start: 1641945600,
                          end: 1642125600,
                          resource:
                            "resource-82219cbb-62f1-4533-8846-4181299fbf3d",
                          chart: {
                            tasks: [
                              {
                                id: "6b85183b-fe28-4e83-9f04-6834036cf446",
                                name: "Task 1",
                                start: 1641945600,
                                end: 1642125600,
                                resource:
                                  "resource-82219cbb-62f1-4533-8846-4181299fbf3d",
                                chart: { omit: "......." },
                              },
                            ],
                          },
                        },
                      ],
                    },
                  },
                ],
              },
            },
          ],
        },
      };
```

**Comment by Sarmerer** [comment]
It won't cause memory overflow, unless you don't have a tiny amount of RAM in your system. Each task stores only a reference to a chart object. No matter how many tasks you have, they will reference the same and single chart
